### PR TITLE
Fix audit logs by updating package-lock.json (with `npm audit --fix`)

### LINKED ISSUE #7: npm audit warning `High`
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint-config-airbnb-standard [dev]                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint-config-airbnb-standard > babel-eslint >               │
│               │ @babel/traverse > @babel/generator > lodash                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by sidoruk-sv**
fixes #7

### CODE REVIEW

**Comment by sidoruk-sv** [comment]
@doasync, please review

**Comment by scott-ln** [comment]
@doasync hasn't made any contributions since last June so it seems unlikely this will get approved any time soon. In the meantime I've found the package [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions) as a workaround.

**Comment by doasync** [comment]
Updated in 3.1.0

**Comment by scott-ln** [comment]
Thank you @doasync!

**Pull request closed without merging**
